### ISSUE TITLE
Issue with joystick?

### ISSUE THREAD

**Issue by lostinblue** [tanema/amore#2]
../../src/github.com/tanema/amore/joystick/joystick.go:36: cannot use joystick.id (type int) as type sdl.JoystickID in argument to sdl.JoystickOpen

**Comment by bruston** [comment]
I'm not sure how to use Glock for dependency management but if you manually checkout the commit shown in the Glockfile https://github.com/tanema/amore/blob/master/Glockfile for the package github.com/veandco/go-sdl2 (commit is a8fc14d68096cfbb00cfe247cf947ef4ea4407d0) it should build.

**Comment by tanema** [comment]
I have been trying to keep these two packages in line, so I will check out the most recent sdl package and check that out.

**Comment by tanema** [comment]
Thanks for catching that and thanks @bruston for the help.

**Comment by lostinblue** [comment]
No problem, thanks for fixing it so quickly.

**Comment by lostinblue** [comment]
Do you have plans to make this language cross mobile platforms too using the gomobile library?
